# Generated by Django 3.2.25 on 2025-04-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250402_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usernickname',
        ),
    ]
