# Generated by Django 3.2.25 on 2024-11-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_about_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'информацию о нас', 'verbose_name_plural': 'информацию о нас'},
        ),
        migrations.AlterModelOptions(
            name='contactlink',
            options={'verbose_name': 'ссылку на контакт', 'verbose_name_plural': 'Ссылки на контакты'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='imageabout',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальную сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
